version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  docker: circleci/docker@2.6.0

jobs: 
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v2-{{ checksum "MathApp/MathApp.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v2-{{ checksum "MathApp/MathApp.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage

   
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release

  docker-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: docker.io/latest:3d785b54eeef99ec7ebf3e694212886b19e4001d 
     

workflows:
  test_and_build:
    jobs:
      - docker-job
      - test
      - build:
          requires:
            - test
    